
spring:
  jpa:
    generate-ddl: true
    show-sql: true
  data:
    redis:
      host: middle-dev.vhsoft.cn
      port: 16379
      password: V20Hsoft@4
      client-name: ${spring.application.name}
      database: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost/demo1?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=PRC&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 20
      max-wait: 60000
      min-idle: 5
      connection-init-sqls:
        - set names utf8mb4

management:
  health:
    defaults:
      enabled: true
